# Generated by Django 4.2.20 on 2025-04-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nfc_id',
            field=models.CharField(max_length=100),
        ),
    ]
